Data storage
umr-lops/Data pull request #1
Opened 2023-10-11 12:38 UTC by quai20

2023-10-17 14:06 UTC, quai20 commented
@tristanlt : si tu as le temps de checker que j'ai pas marqué de betises sur la partie stockage côté iuem.
@EPauthenet : si tu peux regarder un peu tout et tester la branche chez toi avec hugo, merci.

2023-10-18 09:22 UTC, EPauthenet requested changes

2023-10-18 11:38 UTC, quai20 commented on content/store/datarmor/access.md
> +
J'avais mis le lien vers la doc de Tristan justement pour ça, car je voulais pas vraiment faire un tuto datarmor. Mais on peut ajouter 2/3 rappels avec les commandes de bases

2023-10-18 11:39 UTC, quai20 commented on content/store/datarmor/access.md
> +---
bien vu

2023-10-18 13:40 UTC, quai20 commented on content/store/datarmor/access.md
> +---
:+1:

2023-10-18 13:42 UTC, merged